/**
 * @license
 * Copyright 2021 Google LLC. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * =============================================================================
 */

// This file is autogenerated.


import {registerKernel} from '@tensorflow/tfjs-core/dist/base';
import '@tensorflow/tfjs-core/dist/base_side_effects';
export * from '@tensorflow/tfjs-core/dist/base';
export * from '@tensorflow/tfjs-converter';

//backend = cpu
export * from '@tensorflow/tfjs-backend-cpu/dist/base';
import {fromPixelsConfig as FromPixels_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/FromPixels';
registerKernel(FromPixels_cpu);
import {castConfig as Cast_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Cast';
registerKernel(Cast_cpu);
import {expandDimsConfig as ExpandDims_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/ExpandDims';
registerKernel(ExpandDims_cpu);
import {rotateWithOffsetConfig as RotateWithOffset_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/RotateWithOffset';
registerKernel(RotateWithOffset_cpu);
import {cropAndResizeConfig as CropAndResize_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/CropAndResize';
registerKernel(CropAndResize_cpu);
import {realDivConfig as RealDiv_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/RealDiv';
registerKernel(RealDiv_cpu);
import {fusedConv2DConfig as FusedConv2D_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/FusedConv2D';
registerKernel(FusedConv2D_cpu);
import {depthwiseConv2dNativeConfig as DepthwiseConv2dNative_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/DepthwiseConv2dNative';
registerKernel(DepthwiseConv2dNative_cpu);
import {addConfig as Add_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Add';
registerKernel(Add_cpu);
import {preluConfig as Prelu_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Prelu';
registerKernel(Prelu_cpu);
import {maxPoolConfig as MaxPool_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/MaxPool';
registerKernel(MaxPool_cpu);
import {padV2Config as PadV2_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/PadV2';
registerKernel(PadV2_cpu);
import {reshapeConfig as Reshape_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Reshape';
registerKernel(Reshape_cpu);
import {identityConfig as Identity_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Identity';
registerKernel(Identity_cpu);
import {sigmoidConfig as Sigmoid_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Sigmoid';
registerKernel(Sigmoid_cpu);
import {resizeBilinearConfig as ResizeBilinear_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/ResizeBilinear';
registerKernel(ResizeBilinear_cpu);

//backend = webgl
export * from '@tensorflow/tfjs-backend-webgl/dist/base';
import {fromPixelsConfig as FromPixels_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/FromPixels';
registerKernel(FromPixels_webgl);
import {castConfig as Cast_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Cast';
registerKernel(Cast_webgl);
import {expandDimsConfig as ExpandDims_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/ExpandDims';
registerKernel(ExpandDims_webgl);
import {rotateWithOffsetConfig as RotateWithOffset_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/RotateWithOffset';
registerKernel(RotateWithOffset_webgl);
import {cropAndResizeConfig as CropAndResize_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/CropAndResize';
registerKernel(CropAndResize_webgl);
import {realDivConfig as RealDiv_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/RealDiv';
registerKernel(RealDiv_webgl);
import {fusedConv2DConfig as FusedConv2D_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/FusedConv2D';
registerKernel(FusedConv2D_webgl);
import {depthwiseConv2dNativeConfig as DepthwiseConv2dNative_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/DepthwiseConv2dNative';
registerKernel(DepthwiseConv2dNative_webgl);
import {addConfig as Add_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Add';
registerKernel(Add_webgl);
import {preluConfig as Prelu_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Prelu';
registerKernel(Prelu_webgl);
import {maxPoolConfig as MaxPool_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/MaxPool';
registerKernel(MaxPool_webgl);
import {padV2Config as PadV2_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/PadV2';
registerKernel(PadV2_webgl);
import {reshapeConfig as Reshape_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Reshape';
registerKernel(Reshape_webgl);
import {identityConfig as Identity_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Identity';
registerKernel(Identity_webgl);
import {sigmoidConfig as Sigmoid_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Sigmoid';
registerKernel(Sigmoid_webgl);
import {resizeBilinearConfig as ResizeBilinear_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/ResizeBilinear';
registerKernel(ResizeBilinear_webgl);